# Generated by Django 3.0.8 on 2021-06-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hla', 'init_locus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='testRunID',
            field=models.CharField(default='unknown', max_length=30, unique=True),
        ),
    ]
