# Generated by Django 3.0.8 on 2021-06-09 16:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hla', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locus',
            fields=[
                ('locusID', models.AutoField(primary_key=True, serialize=False)),
                ('locusName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('patientNumber', models.CharField(default='unknown', max_length=15, unique=True)),
                ('patientID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('resultID', models.AutoField(primary_key=True, serialize=False)),
                ('result', models.CharField(max_length=20)),
                ('alleleFreq', models.CharField(default='NA', max_length=20)),
                ('externalInfo', models.URLField(max_length=100, null=True)),
                ('locusID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hla.Locus')),
                ('patientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hla.Patients')),
            ],
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('testID', models.AutoField(primary_key=True, serialize=False)),
                ('testRunID', models.CharField(default='unknown', max_length=30)),
                ('testDate', models.DateTimeField(default=datetime.datetime.now, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='LogMessage',
        ),
        migrations.AddField(
            model_name='results',
            name='testID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hla.Tests'),
        ),
    ]
