# Generated by Django 3.0.8 on 2022-03-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hla', '0001_auto_20210609_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='externalInfo',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
