# Generated by Django 3.0.8 on 2022-03-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hla', '0002_auto_20220309_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='uploader',
            field=models.CharField(default='unknown', max_length=30),
        ),
    ]
