
# Generated by Django 3.0.8 on 2020-08-26 16:52

from django.db import migrations

HLA_LOCI = (
    'HLA-A',
    'HLA-B',
    'HLA-C',
    'HLA-DPA1',
    'HLA-DPB1',
    'HLA-DQA1',
    'HLA-DQB1',
    'HLA-DRB1',
    'HLA-DRB3/4/5',
)


def add_loci(apps, schema_editor):
    Locus = apps.get_model('hla', 'Locus')

    for locus in HLA_LOCI:
        locusType = Locus(locusName=locus)
        locusType.save()


class Migration(migrations.Migration):

    dependencies = [
        ('hla', '0001_auto_20210609_1641'),
    ]

    operations = [
        migrations.RunPython(add_loci),
    ]