# Generated by Django 3.0.7 on 2020-06-15 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hla', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LogMessage',
            new_name='ImportData',
        ),
    ]
