# Generated by Django 3.0.8 on 2020-08-06 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hla', '0003_hla_results'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locus',
            fields=[
                ('locusID', models.AutoField(primary_key=True, serialize=False)),
                ('locusName', models.CharField(max_length=30)),
                ('allele', models.CharField(choices=[('1', 'one'), ('2', 'two')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('patientID', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('resultID', models.AutoField(primary_key=True, serialize=False)),
                ('result', models.CharField(max_length=20)),
                ('locusID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hla.Locus')),
            ],
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('testID', models.AutoField(primary_key=True, serialize=False)),
                ('confirmed', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], max_length=1)),
                ('patientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hla.Patients')),
            ],
        ),
        migrations.DeleteModel(
            name='HLA_Results',
        ),
        migrations.AddField(
            model_name='result',
            name='testID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hla.Tests'),
        ),
    ]
