# Generated by Django 3.0.8 on 2020-08-06 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hla', '0004_auto_20200806_1739'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Result',
            new_name='Results',
        ),
        migrations.AddField(
            model_name='tests',
            name='testDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
