# Generated by Django 3.0.8 on 2020-08-25 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hla', '0005_auto_20200806_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locus',
            name='allele',
        ),
        migrations.RemoveField(
            model_name='tests',
            name='patientID',
        ),
        migrations.AddField(
            model_name='patients',
            name='patientName',
            field=models.CharField(default=None, max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='results',
            name='patientID',
            field=models.ForeignKey(default='def', on_delete=django.db.models.deletion.CASCADE, to='hla.Patients'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patients',
            name='patientID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
