# Generated by Django 3.0.8 on 2020-09-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hla', '0007_auto_20200826_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='patientName',
        ),
        migrations.AddField(
            model_name='patients',
            name='patientNumber',
            field=models.CharField(default=None, max_length=15, unique=True),
        ),
    ]
