# Generated by Django 3.0.8 on 2020-09-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hla', '0008_auto_20200904_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='patientNumber',
            field=models.CharField(default='unknown', max_length=15, unique=True),
        ),
    ]
