# Generated by Django 3.0.8 on 2020-09-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hla', '0010_auto_20200918_1545'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImportData',
        ),
        migrations.RemoveField(
            model_name='tests',
            name='confirmed',
        ),
        migrations.AddField(
            model_name='results',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
